### ISSUE TITLE
gatsby build => window is not defined

### ISSUE THREAD

**Issue by Wursthandschuh** [davidcetinkaya/embla-carousel-react#1]
if you build  a gatsby app you get this:
>8 |  else
   9 |          root["EmblaCarousel"] = factory();
 10 | })(window, function() {
     |  ^
  11 | return /******/ (function(modules) { // webpackBootstrap
  12 | /******/         // The module cache
  13 | /******/         var installedModules = {};

  WebpackError: ReferenceError: window is not defined
  
  - index.js:10 Object../node_modules/embla-carousel/lib/index.js
    [lib]/[embla-carousel]/lib/index.js:10:2

Problem only occurs with gatsby build. gatsby develop works fine

**Comment by davidcetinkaya** [comment]
Hi @Wursthandschuh,
Thank you very much for reporting this 👍! 

This seems to be caused by a Webpack 4 bug, see this [Stackoverflow issue](https://stackoverflow.com/questions/49111086/webpack-4-universal-library-target). Basically, webpack 4 includes `window` when creating a `UMD` bundle but it shouldn't.

I'll let you know as soon as I've tried a suggested workaround.

**Comment by davidcetinkaya** [comment]
Hello again WIlli (@Wursthandschuh),

I've implemented one of the suggested workarounds for this issue. Please try [v0.1.2](https://github.com/davidcetinkaya/embla-carousel-react/releases/tag/v0.1.2) by installing the latest package like so:

```bash
npm install embla-carousel-react@0.1.2
```
or

```bash
yarn add embla-carousel-react@0.1.2
```

I'd very much appreciate if you can confirm if this fixes the issue.

Thank you in advance 👍!

**Comment by Wursthandschuh** [comment]
Hi @davidcetinkaya ,
the fix works! Thank you for the quick response and fixing =)
Keep up the good work on this project 👍

**Comment by davidcetinkaya** [comment]
Thanks a lot @Wursthandschuh, cheers 🙂!
