### ISSUE TITLE
 Cannot read property 'removeAllEvents' of undefined

### ISSUE THREAD

**Issue by omarkhatibco** [davidcetinkaya/embla-carousel-react#13]
Hi @davidcetinkaya 

I have a problem with the new Embla React version, I think `1.2.18` ~ `1.2.19`

Now when I do `embla.destroy()` in `useEffect` I get this message `Cannot read property 'removeAllEvents' of undefined`. it has worked before.

I traced it back in source code, it is here 

```js
  function deActivate() {
    engine.dragHandler.removeAllEvents(); // the problem is here
    engine.animation.stop();
    eventStore.removeAll();
    root.classList.remove(options.draggableClass);
    container.style.transform = '';
    slides.forEach(function (s) {
      return s.style.left = '';
    });
  }
```
Thanks
Omar

**Comment by davidcetinkaya** [comment]
Thanks a lot for reporting this Omar (@omarkhatibco) 👍!
I'll take a look at it as soon as possible and get back to you as soon as I have something.

**Comment by davidcetinkaya** [comment]
Hello again Omar (@omarkhatibco),

After investigating this further, this is because the destruction of the Embla instance has been **moved into the package core** since [version 1.2.11](https://github.com/davidcetinkaya/embla-carousel-react/releases/tag/1.2.11). So if you're doing this manually you'll have to remove it like so:

```javascript
useEffect(() => {
  ...

  return () => embla && embla.destroy(); // You'll have to remove this line
}, [embla]);
```

You can also check this [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-13-t7f2u) out where you can click the **Toggle Embla** button and see it in action without that piece of code.

Thanks a lot for reporting this and let me know if it solves your issue.

Best,
David

**Comment by omarkhatibco** [comment]
Hi @davidcetinkaya
I have already did that, thanks for your feedback.
