### ISSUE TITLE
Not initiating properly from Gatsby internal pages

### ISSUE THREAD

**Issue by ndimatteo** [davidcetinkaya/embla-carousel-react#30]
Hi there @davidcetinkaya! I've been using this plugin on a handful of projects without issue, and have been loving it! Kudos!

Unfortunately, today I encountered an issue when using this in conjunction with Gatsby and their internal [Link](https://www.gatsbyjs.org/docs/gatsby-link/) feature that allows you to programmatically navigate between pages.

When I navigate to a page with my `EmblaCarouselReact` component, the carousel container that is supposed to receive the `transform` is completely absent and I can't drag, click, etc... causing the entire carousel to **fail to move**:

![wtf-embla](https://user-images.githubusercontent.com/737188/83922985-59426580-a74f-11ea-9299-215cdbf6d8cd.gif)

Live example: https://misfit-toys.netlify.app/

And here's my carousel component code:
```js
import React, { useState, useEffect, useCallback } from 'react'
import { useEmblaCarousel } from 'embla-carousel-react'
import { useInterval } from '../lib/helpers'
import LazyLoad from 'vanilla-lazyload'

const ImageCarousel = ({ autoplay, photos }) => {
  const [EmblaCarouselReact, embla] = useEmblaCarousel({ speed: 6, loop: true })
  const [selectedIndex, setSelectedIndex] = useState(0)
  const [scrollSnaps, setScrollSnaps] = useState([])
  const [isPaused, setIsPaused] = useState(!autoplay)

  const scrollNext = useCallback(() => embla.scrollNext(), [embla])
  const scrollTo = useCallback((index) => embla.scrollTo(index), [embla])

  if (autoplay) {
    useInterval(() => {
      if (!isPaused) {
        scrollNext()
      }
    }, 5000)
  }

  useEffect(() => {
    const onSelect = () => {
      setSelectedIndex(embla.selectedScrollSnap())
    }
    if (embla) {
      setScrollSnaps(embla.scrollSnapList())
      embla.on('select', onSelect)
      onSelect()
    }
  }, [embla])

  useEffect(() => {
    let lazy = new LazyLoad({
      elements_selector: '.photo',
      threshold: -100,
      class_loaded: 'is-loaded',
    })

    return () => {
      lazy.destroy()
    }
  }, [])

  return (
    <div
      className="carousel--wrapper"
      onMouseEnter={() => setIsPaused(true)}
      onMouseLeave={() => setIsPaused(false)}
    >
      <EmblaCarouselReact className="carousel">
        <div className="carousel--container">
          {photos.map((photo, index) => (
            <div className="carousel--slide" key={index}>
              <div className="is-aspect is-aspect--landscape">
                <img className="photo" data-src={photo.src} alt={photo.alt} />
              </div>
            </div>
          ))}
        </div>
      </EmblaCarouselReact>

      {scrollSnaps && (
        <div className="carousel--nav">
          {scrollSnaps.map((snap, index) => (
            <button
              className={`carousel--dot${
                index === selectedIndex ? ' is-active' : ''
              }`}
              onClick={() => scrollTo(index)}
              key={index}
              aria-label={`Go to slide ${index + 1}`}
            />
          ))}
        </div>
      )}
    </div>
  )
}

export default ImageCarousel
```

Any ideas here?

**Comment by davidcetinkaya** [comment]
Hello Nick (@ndimatteo),

Thank you I'm glad you like Embla Carousel 🙂.

Unfortunately I'm not familiar with Gatsby. Here's a [CodeSandbox](https://codesandbox.io/s/csstransition-react-router-qrhnh) with React Router that works as intended. I'm tossing it your way in case it will help you with to understand why this is happening. I will take a closer look at this as soon as possible. In the meantime, I'm going to add the label `help wanted` and see if we have any Gatsby users willing to help out.

Also, it would help if you could provide a CodeSandbox test case instead of the live link so I can debug what's going on. I would appreciate that.

@Wursthandschuh, @louMoxy, @davemullenjnr any ideas?

Kindly,
David

**Comment by louMoxy** [comment]
Hi @ndimatteo

Yeah, it's hard to debug without a sandbox, but my best guess would be that the issue is the lazyload library, as I would recommend not using that library and switching it for [Gatsby image](https://www.gatsbyjs.org/packages/gatsby-image/). Which works fine with Embla as I have used it on a [gatsby site](https://naomidaviesjewellery.co.uk/) before. 

I haven't used the lazyload myself but looks like the library would need some more hooks to handle the react component updating, found and [example here](https://codesandbox.io/s/20306yk96p?file=/src/lazy-image.js)

But I would really recommend using the gatsby image, I have found it really improves performance. Happy to provide code example if needed. 

Hope this helps, 
Louise

**Comment by ndimatteo** [comment]
Thanks @davidcetinkaya and @louMoxy !

So, I don't think it has anything to do with the image lazy-loading, as I have aspect-ratio containers for those, so the slider should still work regardless of that component.

Just to be sure, I removed the lazyload component completely and still encountered the same problem.

I'd LOVE to get you a sandbox of this, but I can't seem to get codesandbox to work with Gatsby. For now, I've been able to temporarily fix this by forcing it to rejig with the following in the carousel `useEffect`:

```javascript
setTimeout(() => {
  embla.changeOptions({})
}, 500)
```
_FYI: The timeout speed is the same as my page transition speed, so there's no delay/flicker in seeing the carousel update_

**Comment by davidcetinkaya** [comment]
Thank you for the update Nick (@ndimatteo).

The CodeSandbox Gatsby started didn’t work? Did you try this one👇🏻?

![5720F56C-A885-47E9-9306-818B9DE27C98](https://user-images.githubusercontent.com/11529148/84065870-5650aa80-a9c5-11ea-824c-bcfa846f83e8.png)

If you log the children count from your carousel component, what do you get by the time the Embla is initialized?

Kindly,
David

**Comment by ndimatteo** [comment]
No problem! And yea that's the exact one I tried, but it kept giving me a server error just trying to spin one up :/

I know this is a bit of a big ask, but if you're open to it, I'd be happy to add you to the repo so you could spin it up locally. Would at least give you the same setup that I have where the problem persists?

And if I log the `photos` prop above my `return` in my carousel component I get all 3 images being returned consistently (both on hard load and navigating to that page from another).

**Comment by davidcetinkaya** [comment]
@ndimatteo I could give it a try, but can’t promise when. You may add me to the repo and I’ll take a look when I can. So this also happens when the dev server is running right?

**Comment by ndimatteo** [comment]
@davidcetinkaya no problem at all! My fallback solution is working for now so I'm in no rush, just curious what this could be.

I just added you to the repo, holler if you have any issues getting it up and running.

And yes, it's happening both when the dev server is running, and in production.

**Comment by davidcetinkaya** [comment]
Hello Nick (@ndimatteo),

I cloned your repository and started investigating why this is happening and don't think this is related to the [`Gatsby Link component`](https://www.gatsbyjs.org/docs/gatsby-link/). Seems like the [`framer-motion`](https://github.com/framer/motion) library is causing this.

Because if I comment the motion component in this file: `src/containers/layout.js` like so:

```jsx
const Layout = ({ children, location }) => {
  return (
    <Wrapper>
      {/* <AnimatePresence initial={false}>
        <motion.div
          id="page"
          key={location.pathname}
          variants={variants}
          initial="initial"
          animate="enter"
          exit="exit"
        > */}

      {children}

      {/* </motion.div>
      </AnimatePresence> */}
    </Wrapper>
  )
}
```

...Embla works just fine when navigating with the [`Gatsby Link component`](https://www.gatsbyjs.org/docs/gatsby-link/). I haven't had the time to understand why and how the  [`framer-motion`](https://github.com/framer/motion) library is causing this, and most importantly how to solve it, but at least you should know where to start digging now 🙂.

I hope this helps?

Cheers!
David

**Comment by davidcetinkaya** [comment]
**Update**

I briefly browsed the documentation and found the [`exitBeforeEnter`](https://www.framer.com/api/motion/animate-presence/#animatepresenceprops.exitbeforeenter) prop for the `<AnimatePresence>` component. Using this prop seems to solve the issue:

```jsx
const Layout = ({ children, location }) => {
  return (
    <Wrapper>
      <AnimatePresence initial={false} exitBeforeEnter> // Add exitBeforeEnter here
        <motion.div
          id="page"
          key={location.pathname}
          variants={variants}
          initial="initial"
          animate="enter"
          exit="exit"
        >
          {children}
        </motion.div>
      </AnimatePresence>
    </Wrapper>
  )
}
```

Please note that the [`exitBeforeEnter`](https://www.framer.com/api/motion/animate-presence/#animatepresenceprops.exitbeforeenter) prop is in **`beta`** though.

Let me know if this helps!
David

**Comment by ndimatteo** [comment]
@davidcetinkaya thank you so much for taking a look at this! That is SUPER helpful!

No idea why that prop seems to do the trick, but I'll take it! Again, thanks a bunch 🙌

**Comment by davidcetinkaya** [comment]
Hello Nick (@ndimatteo), 

I’m glad it helped 👍🏻.

My initial hunch was that some library was doing things under the hood, causing a race condition or similar. When I inactivated the animation lib responsible for the page transitions, it worked as expected so that was a strong indication that I was on the right track, freeing the Gatsby link component from blame 🙂.

If you have a moment, I’d appreciate if you would vote about Embla Version 3 [here](https://github.com/davidcetinkaya/embla-carousel/issues/67).

If you get to like Embla and it grows on you, please share it with colleagues and friends, or consider giving it a ⭐️. Any of this boosts my motivation for making this lib better 😃.

Thank you and cheers!
David
